name = "kebo-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

[env.staging]
name = "kebo-api-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "kebo-api"
vars = { ENVIRONMENT = "production" }

[observability]
enabled = true
